name: Diagram

on:
  push:
    branches:
      - repo-visualizer

permissions:
  contents: write

jobs:
  update-diagram:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      uses: githubocto/repo-visualizer@main
      with:
        excluded_paths: "server/.sqlx,.github,diagram.svg"
        commit_message: "[action] Updated diagram [skip ci]"
